Changed get_log simply to rsync log directory

diff --git a/get_log b/get_log
--- a/get_log
+++ b/get_log
@@ -24,21 +24,9 @@ year=`date +%Y`
 local_log_dir=$logs_dir/$log_dir/$year
 mkdir -p $local_log_dir
 
-log_file=$local_log_dir/${date_stamp}.log.gz
-log_link=$local_log_dir/${log_prefix}.gz
+rsync_copy_changes $remote_logs_dir/${log_prefix}-*.gz $local_log_dir > $command_log_file
 
-rsync_copy_changes $remote_logs_dir/${log_prefix}-${todays_date}.gz $log_file > $command_log_file
-
-if [ -h $log_link ]; then
-    diff $log_link $log_file > /dev/null
-
-    if [ "$?" == "0" ]; then
-	rm $log_file
-	exit
-    else
-	rm $log_link
-    fi
+if [[ $? -ne 0 ]]; then
+    echo "*** Failed to get log files ***"
+    cat {$command_log_file}
 fi
-
-echo "New log file downloaded $log_file"
-ln -s $log_file $log_link
